# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(600, 320, 400, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 1600, 100))
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 410, 1600, 800))
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.label_userscore = QtWidgets.QLabel(self.centralwidget)
        self.label_userscore.setGeometry(QtCore.QRect(510, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_userscore.setFont(font)
        self.label_userscore.setObjectName("label_userscore")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(20, 90, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.label_compscore = QtWidgets.QLabel(self.centralwidget)
        self.label_compscore.setGeometry(QtCore.QRect(1540, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_compscore.setFont(font)
        self.label_compscore.setObjectName("label_compscore")
        self.label_computer = QtWidgets.QLabel(self.centralwidget)
        self.label_computer.setGeometry(QtCore.QRect(1090, 100, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_computer.setFont(font)
        self.label_computer.setObjectName("label_computer")
        self.comboBox_selection = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_selection.setGeometry(QtCore.QRect(600, 200, 400, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_selection.setFont(font)
        self.comboBox_selection.setObjectName("comboBox_selection")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project1"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.label_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#ff5500;\">Rock</span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">, </span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#0055ff;\">Paper,</span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#55ff00;\"/><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#55ff00;\">Scissors!</span></p></body></html>"))
        self.label_result.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#0000ff;\">Good Luck!!!</span></p></body></html>"))
        self.label_userscore.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">0</span></p></body></html>"))
        self.label_user.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">User Score</span></p></body></html>"))
        self.label_compscore.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">0</span></p></body></html>"))
        self.label_computer.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Computer Score</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
